# Generated by Django 6.0.3 on 2026-03-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
