# Generated by Django 6.0.3 on 2026-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="дополнительные данные"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Успешно оплачен"),
                    ("canceled", "Отменен"),
                    ("failed", "Ошибка"),
                    ("refunded", "Возвращен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_checkout_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="ссылка на оплату Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID PaymentIntent в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии в Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "наличные"),
                    ("transfer", "перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                default="transfer",
                max_length=50,
            ),
        ),
    ]
