[tool.poetry]
name = "lms-system"
version = "0.1.0"
description = ""
authors = ["Nikita Dorozhko <nick.dorozhko@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.3"
psycopg2-binary = "^2.9.11"
pillow = "^12.1.1"
djangorestframework = "^3.16.1"
python-dotenv = "^1.2.2"
django-filter = "^25.2"
djangorestframework-simplejwt = "^5.5.1"
coverage = "^7.13.5"
drf-yasg = "^1.21.15"
requests = "^2.32.5"
celery = "^5.6.2"
redis = "^7.4.0"
django-celery-beat = "^2.9.0"
ipython = "^9.11.0"
dj-database-url = "^3.1.2"
gunicorn = "^25.3.0"
flake8 = "^7.3.0"


[tool.poetry.group.linters.dependencies]
mypy = "^1.19.1"
isort = "^8.0.1"
black = "^26.1.0"
flake8 = "^7.3.0"


[tool.poetry.group.dev.dependencies]
black = "^26.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
