# Generated by Django 6.0.3 on 2026-03-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите название курса",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to="courses_preview/", verbose_name="превью"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание курса", verbose_name="описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите название урока",
                        max_length=150,
                        verbose_name="название",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "preview",
                    models.ImageField(
                        upload_to="lessons_preview", verbose_name="превью"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        help_text="добавьте ссылку на видео",
                        max_length=100,
                        verbose_name="ссылка",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="lms.course",
                        verbose_name="курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
    ]
