# Generated by Django 6.0.3 on 2026-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_subscription_options_subscription_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lessons_preview",
                verbose_name="превью",
            ),
        ),
    ]
