# Generated by Django 6.0.3 on 2026-03-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_alter_lesson_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="courses_preview/",
                verbose_name="превью",
            ),
        ),
    ]
