# Generated by Django 6.0.3 on 2026-03-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="дата отправки последнего уведомления",
            ),
        ),
    ]
